### PR TITLE
Adding lowess

### PR DESCRIPTION
**Pull request by ayushpatnaikgit**
We have implemented [Lowess](https://github.com/xKDR/Lowess.jl) in Julia. It has been hand-translated from C. It is the univariate smoothing algorithm that Cleveland had proposed in 1979.

Base R exports both ```lowess``` and ```loess```. While loess can also do univariate, ```lowess``` can be a lot faster, as shown in the benchmarks in [Lowess's Readme file](https://github.com/xKDR/Lowess.jl). Issue #47 is the reason we developed ```lowess```. 
  
We thought of releasing Lowess as a separate package, but based on the discussions here: https://github.com/JuliaRegistries/General/pull/63100, we felt it could be worthwhile discussing if ```lowess``` could be a part of Loess.  We are initiating this PR to discuss this possibility. 

We have made the following changes: 
1) Added tests/lowess.jl: this contains the test for ```lowess```. We have included this file in runtests.jl
2) Added src/lowess.jl: this contain the ```lowess``` function. We have also included this file in Loess.jl and exported ```lowess```. 
3) Updated the readme file to include information about ```lowess```. This file has entirely changed, but we have retained all the information about loess.  

The ```lowess``` code has been translated with minimal changes and the results have been tested against the original code using ccall. Some of those tests have been included in the tests directory. 

In case the merge happens, can we have a documentation where I can lay out more information? This could include definitions of the parameters, differences between loess & lowess, etc. Furthermore, [Lowess.jl](https://github.com/xKDR/Lowess.jl) will be archived after the merge.   

Since we are doing a PR from an organisation, GitHub doesn't allow the owners of Loess to introduce changes to the PR. If someone wants to make a change, I can give you write permissions to the fork.  

**References:** 
Gordon Smyth (2020). Difference between LOESS and LOWESS. https://stats.stackexchange.com/users/129321/gordon-smyth

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks. Do you know what is the license of the original code? I see Lowess.jl is licensed under GPL, but this repo uses the MIT license. If the original code is MIT or public domain it can be merged but otherwise this would require relicensing the package to GPL, which we probably don't want to do.

**Comment by ayushpatnaikgit** [comment]
@nalimilan thanks for the response. I am not very knowledgable about licenses. 

The original code, by Bill Cleveland, can be found here: https://www.netlib.org/go/lowess.f
it just mentions the name of the author and the institute. What do you suggest?

**Comment by nalimilan** [comment]
OK. Unfortunately code distributed by Netlib doesn't have a clear license. Given that R ships a copy of that file under the GPL for years it's probably safe to assume it can be used freely. Would you mind asking him for authorization to distribute work derived from his code under the MIT license though?

**Comment by ayushpatnaikgit** [comment]
Thanks a lot @nalimilan
I think the license in Lowess.jl is possibly incorrect anyway, so I'll remove until there is clarity, and make a note to prevent confusion. I will ask Bill Cleveland & Tony Rossini, and let you know. 

It was an experiment, if it works out, I can do numerous similar translations with my team.

**Comment by ayushpatnaikgit** [comment]
Okay, I discussed the matter with Bill Cleveland. I discussed his response with Viral and Milan, and it seems fine to use an MIT License. So now we can discuss whether we want to add ```lowess``` to Loess without worrying about the license.

**Comment by ViralBShah** [comment]
Can we merge this? 

@nalimilan Given that @ayushpatnaikgit is shepherding this package, should we give him commit access? There are some other simple PRs and housekeeping he can do.

**Comment by nalimilan** [comment]
Sure. But we need somebody to review the PR first, and that's not super easy... :-/

**Comment by ViralBShah** [comment]
One of our challenges is that we do not have enough folks in JuliaStats to review PRs. How should we onboard new developers? 

If the testsuite is substantial enough, can we use that to ease the path to merging? Perhaps this is more of a discourse discussion issue.

**Comment by ViralBShah** [comment]
@nalimilan Given that review bandwidth is hard, wouldn't it be better to go along with the original plan of registering Lowess.jl as a separate package so that @ayushpatnaikgit can keep developing at his own pace. Thoughts? I feel that registering the package is low cost, and there's always the opportunity at a later point to merge here.

**Pull request closed without merging**
