### PR TITLE
Fix loess dispatch to avoid infinite recursion

### PR DESCRIPTION
**Pull request by frankier**
Fixes https://github.com/JuliaStats/Loess.jl/issues/60

### CODE REVIEW

**Comment by andreasnoack** [comment]
Thanks for looking into this. Could you please add a test as well?

**Comment by frankier** [comment]
I guess a regression test (as added now) works?

**Comment by frankier** [comment]
Anything else to do here?

**Review by andreasnoack — APPROVED** [review]
It would have been great to also run the benchmarks but it seems impossible to get the working when the PR is from a fork, see #96. Anyway, this should be good. Thanks again for fixing this.

**Pull request merged**
